### ISSUE TITLE
FormateToTRS

### ISSUE THREAD

**Issue by liliaoyuan** [itewqq/TemplateSideChannelAttack#1]
Hi there!
it really wokrs! and  is there a tool that can translate other format to trs?

**Comment by itewqq** [comment]
@liliaoyuan Hi, please refer to this repo and the documents from my friend kreel: https://github.com/kreelsama/InspectorTraceHandler

**Comment by liliaoyuan** [comment]
It does help！
---
BTW, a quick question about the code.
This TA demo is really logic and concise.  Just one confusing thing I am strugglng:

I saw init part in TA.py, A real_key had been added into parameters in profiled established part were this key actully a trained-key or  a demo to validate the matching up of template ?
So If I were correct, in a real attack scenario, we’d be testing up to 256 templates in the worst-case way, right?

**Comment by itewqq** [comment]
@liliaoyuan 
The key should be only used in profiling stage to build a good template. 
However, as I was lazy and it's just a demo, the traces in training and attacking phase are using the same real-key byte.
You can refer to this tutorial for the classic template attack setting: http://wiki.newae.com/Template_Attacks

**Comment by liliaoyuan** [comment]
Thanks so a lot!
